spring:
  application:
    name: local
  profiles:
    active: testing

server:
  port: 8080
  servlet:
    context-path: /local

client:
  path: file://null

jdbc:
  type: com.alibaba.druid.pool.DruidDataSource

write:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.144.171.239:3306/local?characterEncoding=utf-8&autoReconnect=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: d,>0I8pEfef#

read:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.144.171.239:3306/local?characterEncoding=utf-8&autoReconnect=true&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: d,>0I8pEfef#


dingding:
  webhookUrl:
    monitor_dingding_broadcast: ""
    phones: ""

logging:
  level:
    com.tunan.mapper: trace


mybatis-plus:
  mapper-locations: classpath*:**/mapper/*Mapper.impl
  typeAliasesPackage: com.local.model
  global-config:
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

